'''
ADD THE FOLLOWING TO A __credentials.py file
'''
#xc_username
#xc_password
#smtp_username
#smtp_password

'''
SETTINGS
'''

'''mail settings'''
subject = 'FlyForFun Cup Luftraumverletzung'

host = 'smtp.gmail.com'
port =  587
imap_host = 'imap.gmail.com'
imap_port =  993
tls =  True
sender = 'Günther Eder <airspace@flyforfun.at>'
to = 'Günther Eder <fly@geder.at>'

'''gmail settings'''
SCOPES = ['https://www.googleapis.com/auth/gmail.compose']
'''get these in your google account via OAUTH2'''
CREDENTIALS_FILE = "__google_credentials.json"
'''is autogenerated after first login'''
TOKEN_FILE = "__google_token.json"

'''pilot emails - dict from pilot name to pilot email'''
PILOT_MAIL_FILE = '__pilot_email.csv'

'''settings'''
MINIMAL_VALIDATION_DISTANCE = 10 # km

'''scrapper/airspace-check config'''
URL_LOGIN = "https://www.xcontest.org/"
#URL_APPROVAL = "https://www.xcontest.org/flyforfuncup/approval/flights/?filter%5Bstatus%5D=W&filter%5Bscored%5D=&filter%5Bdate%5D=&filter%5Bcountry%5D=&filter%5Bcatg%5D=&filter%5Bpilot%5D=&list%5Bsort%5D=pts&list%5Bdir%5D=down&filter%5Bviolation%5D=&filter%5Bairspace%5D="
URL_APPROVAL = "https://www.xcontest.org/flyforfuncup/approval/flights/?filter%5Bstatus%5D=W&filter%5Bscored%5D=Y&filter%5Bdate%5D=&filter%5Bcountry%5D=&filter%5Bcatg%5D=&filter%5Bpilot%5D=&list%5Bsort%5D=pts&list%5Bdir%5D=down&filter%5Bviolation%5D=&filter%5Bairspace%5D="
JAVA_CORRETTO = "/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/java"
'''the actual airspace checker'''
AIR_SPACE_CHECKER = "airspace-check.jar"

DL_DIR = "flights/"
CHROMEPATH = './chromedriver'
FIREFOXPATH = '/opt/homebrew/bin/geckodriver'
FIREFOXBINPATH = r'/Applications/Firefox.app/Contents/MacOS/firefox'
MANUAL_EVAL_DIR = './manual_eval/'
